version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: intellilab-postgres-dev
    environment:
      POSTGRES_DB: intellilab_gc_dev
      POSTGRES_USER: intellilab
      POSTGRES_PASSWORD: intellilab_dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - intellilab-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intellilab -d intellilab_gc_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: intellilab-redis-dev
    command: redis-server --appendonly yes --requirepass intellilab_dev_redis
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - intellilab-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (Development with hot reload)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: intellilab-backend-dev
    environment:
      - DATABASE_URL=postgresql://intellilab:intellilab_dev_password@postgres-dev:5432/intellilab_gc_dev
      - REDIS_URL=redis://:intellilab_dev_redis@redis-dev:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
      - ./backend/models:/app/models
    ports:
      - "8001:8000"
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    networks:
      - intellilab-dev-network
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend (Development with hot reload)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: intellilab-frontend-dev
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - REACT_APP_WS_URL=ws://localhost:8001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend-dev
    networks:
      - intellilab-dev-network
    restart: unless-stopped

  # Development Nginx (for API proxy)
  nginx-dev:
    image: nginx:alpine
    container_name: intellilab-nginx-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend-dev
      - backend-dev
    networks:
      - intellilab-dev-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  intellilab-dev-network:
    driver: bridge 